import Link from "next/link";
import classes from "./TermsOfService.module.css";

const TermsOfServicePage = () => {
  return (
    <div className={classes.page}>
      <h1 className={classes.topic}>Website Terms and Conditions of Use</h1>
      <p className={classes.introPara}>
        Welcome to our website. By accessing and using our website, you agree to
        comply with and be bound by the following terms and conditions of use,
        which govern our relationship with you regarding this website. If you do
        not agree with these terms and conditions, please do not use our
        website.
      </p>
      <h2 className={classes.subTopic}>Terms</h2>
      <p className={classes.para}>
        The terms &quot;we&quot;, &quot;us&quot;, or &quot;our&quot; refer to the owner of this website. The
        term &quot;you&quot; refers to the user or viewer of our website.
      </p>
      <h2 className={classes.subTopic}>Use License</h2>
      <p className={classes.para}>
        Permission is granted to access and use our website for personal,
        non-commercial, and transitory viewing only. You may temporarily
        download one copy of the materials (such as text, images, videos, and
        audio) on our website for personal, non-commercial, and transitory
        viewing only. This is the grant of a license, not a transfer of title,
        and under this license you may not:
      </p>
      <ul className={classes.ul}>
        <li>modify or copy the materials;</li>
        <li>
          use the materials for any commercial purpose or for any public
          display;
        </li>
        <li>attempt to reverse engineer any software used on our website;</li>
        <li>
          remove any copyright or other proprietary notations from the
          materials; or
        </li>
        <li>
          transfer the materials to another person or &quot;mirror&quot; the materials on
          any other server.
        </li>
      </ul>
      <p className={classes.para}>
        We may terminate this license upon violations of any of these
        restrictions. Upon termination, your viewing right will also be
        terminated, and you should destroy any downloaded materials in your
        possession, whether in printed or electronic format.
      </p>
      <p className={classes.para}>
        Our website provide content generated by OpenAI&apos;s models. You should use
        compliance with applicable laws and regulations.Read{" "}
        <Link href="/info/privecy_policy">privecy policy</Link> for more for more
        information. You are responsible for any content you generate using our
        website, and we are not responsible for any liability arising from the
        use of the generated content.
      </p>
      <h2 className={classes.subTopic}>User Consent</h2>
      <p className={classes.para}>
        By using our website, you are consenting to the collection and use of
        your personal data for the generation of personalized content through
        OpenAI&apos;s API. You may withdraw your consent at any time by contacting us
        directly. Please note that withdrawing consent may impact your ability
        to use certain features of our website.
      </p>
      <h2 className={classes.subTopic}>Disclaimer</h2>
      <p className={classes.para}>
        All the materials on our website are provided &quot;as is&quot; without any
        warranty of any kind, whether express or implied. We make no
        representations concerning the accuracy or reliability of the use of the
        materials on our website or otherwise relating to such materials or any
        sites linked to this website.
      </p>
      <h2 className={classes.subTopic}>Limitations of Liability</h2>
      <p className={classes.para}>
        We will not be held accountable for any damages that will arise with the
        use or inability to use the materials on our website, even if we or an
        authorized representative of this website has been notified, orally or
        in writing, of the possibility of such damage. Some jurisdictions do not
        allow limitations on implied warranties or limitations of liability for
        incidental or consequential damages; these limitations may not apply to
        you.
      </p>
      <p className={classes.para}>
        We will not be held liable for any damages arising from the use of our
        website or the generation of personalized content through OpenAI&apos;s API.
        We are not responsible for the accuracy or reliability of any content
        generated through the API and do not endorse any opinions or views
        expressed therein. We reserve the right to terminate user accounts or
        access to our website for violations of our Terms of Service or any
        applicable laws.
      </p>
      <h2 className={classes.subTopic}>Revisions and Errata</h2>
      <p className={classes.para}>
        The materials appearing on our website may include technical,
        typographical, or photographic errors. We do not promise that any of the
        materials on our website are accurate, complete, or current. We may
        change the materials contained on our website at any time without
        notice. We do not make any commitment to update the materials.
      </p>
      <h2 className={classes.subTopic}>Links</h2>
      <p className={classes.para}>
        We have not reviewed all of the sites linked to our website and are not
        responsible for the contents of any such linked site. The inclusion of
        any link does not imply endorsement by us of the site. The use of any
        linked website is at the user’s own risk.
      </p>
      <h2 className={classes.subTopic}>Site Terms of Use Modifications</h2>
      <p className={classes.para}>
        We may revise these terms and conditions of use for our website at any
        time without prior notice. By using this website, you are agreeing to be
        bound by the current version of these terms and conditions of use.
      </p>
      <h2 className={classes.subTopic}>Advertising</h2>
      <p className={classes.para}>
        Our website may display advertisements from third-party advertisers. We
        are not responsible for the content of these advertisements, and any
        interaction or business conducted with these advertisers is solely
        between you and the advertiser.
      </p>
      <h2 className={classes.subTopic}>Your Privacy</h2>
      <p className={classes.para}>
        Please read our Privacy Policy to understand how we collect, use, and
        disclose information about you.
      </p>
      <h2 className={classes.subTopic}>Governing Law</h2>
      <p className={classes.para}>
        Any claim related to our website shall be governed by the laws of
        [insert jurisdiction] without
      </p>
      <p className={classes.updateDetails}>last updated:- 09/03/2023</p>
    </div>
  );
};

export default TermsOfServicePage;
